### ISSUE TITLE
Login Twice Issue

### ISSUE THREAD

**Issue by diksha04051996** [iSarthakGautam/Placementgyaan#1]
The user has to login twice for going to dashboard.

**Comment by iSarthakGautam** [comment]
Thank you for report, will try to fix that asap.

Regards

**Comment by iSarthakGautam** [comment]
It seems to be issue with url, will update once i find fix

**Comment by iSarthakGautam** [comment]
I have rectified the issue. Kindly Check.
i'll close the thread now, if issue persist kindly comment. :)
